app: scloud
app_cn: '小付云平台'
sub_app_cn: '运营管理平台'
company: '小付钱包技术（北京）有限公司'
language: python
port: 9999

# url根路径及静态文件根路径
domain_host: 'http://127.0.0.1:{port}'
url_root: '/scloud'
static_domain: '/static'
static_path: '/static'

# WebSocket地址
ws_host: 'ws://127.0.0.1:9998'
pub_host: 'http://127.0.0.1:9998'

# 是否启用页面调试
debug_page: True

# sesion会话[MemorySessionStore, MemocachedSessionStore, RedisSessionStore, RedisSessionStoreNew]
session_store: RedisSessionStore

redis:
  host: 127.0.0.1
  port: 6379
  expire: 3600
  prefix: scloud
  db: 0

db:
  scheme: mysql
  user: scloud
  pass: scloud
  host: 127.0.0.1
  port: 3306
  name: scloud
  storm: store
  sqlalchemy: session
  connection_string: '{db.scheme}://{db.user}:{db.pass}@{db.host}:{db.port}/{db.name}?charset=utf8'
  # engine: 'MyISAM'
  engine: 'InnoDB'

sqlalchemy:
  echo: True
  pool_size: 100
  pool_recycle: 3600
  isolation_level: 'REPEATABLE READ'

############################################
# LOGGER
############################################
version: 1
formatters:
  simpleFormater:
    #format: '%(asctime)s - %(levelname)s: %(message)s'
    format: '[%(name)s %(levelname)1.1s %(asctime)s %(module)s:%(lineno)d] %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  consoleFormatter:
    (): 'scloud.logkit.ColoredConsoleFormatter'
  date_formatter:
    format: '[%(levelname)1.1s %(asctime)s %(process)s %(threadName)s  %(module)s:%(lineno)d] %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    formatter: consoleFormatter
    level: NOTSET
    stream: ext://sys.stdout
  file:
    class : torweb.logkit.iTimedRotatingFileHandler
    formatter: simpleFormater
    level: NOTSET
    filename: /usr/api-root/logs/scloud/scloud.log
    when: D
  iError:
    class : torweb.logkit.iTimedRotatingFileHandler
    formatter: date_formatter
    level: ERROR
    filename: /usr/api-root/logs/scloud/error.log
    when: D

loggers:
  logger:
    level: DEBUG
    #handlers: [console]
    handlers: 
      - console
  tornado:
    level: NOTSET
    qualname: tornado
    handlers: 
      - file
  iError:
    level: ERROR
    qualname: iError
    handlers: 
      - iError

root:
  level: INFO
  handlers: 
    - console
    - iError
    - file
